const pageId = document.body.dataset.page || 'index';
let activeInput = null;
let state = {score:0, badges:[]};
const storageKey = `topic53Cyber_${pageId}`;
function loadState(){try{const raw=localStorage.getItem(storageKey); if(raw) state=JSON.parse(raw);}catch(e){} updateHud(); state.badges.forEach(id=>markBadge(id));}
function saveState(){localStorage.setItem(storageKey, JSON.stringify(state));}
function updateHud(){const s=document.querySelector('[data-score]'); if(s) s.textContent=state.score; const b=document.querySelector('[data-badges]'); if(b) b.textContent=state.badges.length; const bar=document.querySelector('[data-progress]'); if(bar) bar.style.width=Math.min(100,state.badges.length*20)+'%';}
function addScore(points){state.score+=points; if(state.score<0) state.score=0; updateHud(); saveState();}
function markBadge(id){const el=document.querySelector(`[data-badge="${id}"]`); if(el){el.textContent='Clearance gained';el.classList.add('unlocked');}}
function unlock(id, points=20){if(!state.badges.includes(id)){state.badges.push(id); addScore(points); markBadge(id);} saveState();}
function resetPage(){localStorage.removeItem(storageKey); location.reload();}
function setFeedback(id,msg,good=false){const el=document.getElementById(id); if(el){el.textContent=msg; el.classList.toggle('good',good); el.classList.toggle('try',!good);}}
function norm(v){return String(v||'').trim().toLowerCase().replace(/\s+/g,' ');}
function checkSelects(containerId, feedbackId, badgeId, pass=null){const box=document.getElementById(containerId); let ok=0,total=0; box.querySelectorAll('select[data-answer]').forEach(sel=>{total++; const card=sel.closest('.item,.match-card,.scenario-card,.mini-card,tr') || sel; card.classList.remove('correct','incorrect'); if(norm(sel.value)===norm(sel.dataset.answer)){ok++; card.classList.add('correct');} else card.classList.add('incorrect');}); const needed=pass||total; const good=ok>=needed; setFeedback(feedbackId,`${ok}/${total} correct. ${good?'Clearance gained.':'Review the clues and try again.'}`,good); if(good) unlock(badgeId);}
function checkInputs(containerId, feedbackId, badgeId, pass=null){const box=document.getElementById(containerId); let ok=0,total=0; box.querySelectorAll('input[data-answer]').forEach(inp=>{total++; inp.classList.remove('correct','incorrect'); if(norm(inp.value)===norm(inp.dataset.answer)){ok++; inp.classList.add('correct');} else inp.classList.add('incorrect');}); const needed=pass||total; const good=ok>=needed; setFeedback(feedbackId,`${ok}/${total} correct. ${good?'Clearance gained.':'Use the word bank and check spellings.'}`,good); if(good) unlock(badgeId);}
function checkRadio(containerId, feedbackId, badgeId, pass=null){const box=document.getElementById(containerId); const groups=[...new Set([...box.querySelectorAll('input[type=radio]')].map(i=>i.name))]; let ok=0; groups.forEach(name=>{const chosen=box.querySelector(`input[name="${name}"]:checked`); const card=box.querySelector(`input[name="${name}"]`).closest('.q,.item,.scenario-card,.mini-card'); card.classList.remove('correct','incorrect'); if(chosen && norm(chosen.value)===norm(chosen.dataset.answer)){ok++; card.classList.add('correct');} else card.classList.add('incorrect');}); const needed=pass||groups.length; const good=ok>=needed; setFeedback(feedbackId,`${ok}/${groups.length} correct. ${good?'Clearance gained.':'Look again at the strongest evidence.'}`,good); if(good) unlock(badgeId);}
function checkOrder(listId, feedbackId, badgeId){const list=document.getElementById(listId); const items=[...list.querySelectorAll('li')]; const ok=items.every((li,i)=>Number(li.dataset.rank)===i+1); setFeedback(feedbackId, ok?'Correct order. Clearance gained.':'Not quite. Drag the most urgent or earliest step higher.', ok); if(ok) unlock(badgeId);}
function checkFlags(containerId, feedbackId, badgeId){const box=document.getElementById(containerId); const flags=[...box.querySelectorAll('.click-flag')]; const goodFlags=flags.filter(f=>f.dataset.ok==='1'); const selectedGood=goodFlags.filter(f=>f.classList.contains('selected')).length; const selectedBad=flags.filter(f=>f.dataset.ok!=='1' && f.classList.contains('selected')).length; flags.forEach(f=>{f.classList.remove('correct','incorrect'); if(f.classList.contains('selected')){f.classList.add(f.dataset.ok==='1'?'correct':'incorrect')}}); const good=selectedGood===goodFlags.length && selectedBad===0; setFeedback(feedbackId,`You found ${selectedGood}/${goodFlags.length} real red flags${selectedBad?` and selected ${selectedBad} false clue(s)`:''}. ${good?'Clearance gained.':'Check sender, urgency, link pressure, password requests and threats.'}`,good); if(good) unlock(badgeId);}
function showChecklist(textareaId, feedbackId, badgeId, minWords=25){const text=document.getElementById(textareaId).value.trim(); const words=text?text.split(/\s+/).length:0; const good=words>=minWords; setFeedback(feedbackId, good?`Written response recorded (${words} words). Clearance gained if your answer uses accurate keywords and explains impact/defence.`:`Write a little more detail. Aim for at least ${minWords} words using threat → method → impact → defence.`,good); if(good) unlock(badgeId,25); const check=document.getElementById(feedbackId+'Checklist'); if(check) check.classList.remove('hidden');}
document.addEventListener('click',e=>{if(e.target.classList.contains('click-flag')) e.target.classList.toggle('selected'); if(e.target.dataset.choiceGroup){const group=e.target.dataset.choiceGroup; document.querySelectorAll(`[data-choice-group="${group}"]`).forEach(b=>b.classList.remove('selected')); e.target.classList.add('selected'); const input=document.querySelector(`input[data-choice-store="${group}"]`); if(input) input.value=e.target.dataset.value;}});
document.addEventListener('focusin',e=>{if(e.target.matches('input[data-answer]')) activeInput=e.target;});
function putWord(word){if(activeInput){activeInput.value=word; activeInput.focus();}}
let dragged=null;document.addEventListener('dragstart',e=>{if(e.target.matches('.draggable-list li')) dragged=e.target;});document.addEventListener('dragover',e=>{if(e.target.matches('.draggable-list li')) e.preventDefault();});document.addEventListener('drop',e=>{if(e.target.matches('.draggable-list li')&&dragged){e.preventDefault();const list=e.target.parentNode;const items=[...list.children];const from=items.indexOf(dragged),to=items.indexOf(e.target);if(from<to)list.insertBefore(dragged,e.target.nextSibling);else list.insertBefore(dragged,e.target);}});
loadState();
